import { readdir, writeFile } from 'fs/promises';
import { join, basename } from 'path';
import pino from 'pino';

const logger = pino({ name: 'scene-registry' });

const SCENES_DIR = '/workspace/src/scenes';
const REGISTRY_FILE = '/workspace/src/scene-registry.ts';

export async function generateSceneRegistry(): Promise<void> {
  let sceneFiles: string[] = [];

  try {
    const entries = await readdir(SCENES_DIR);
    sceneFiles = entries.filter(f => f.endsWith('.tsx') || f.endsWith('.ts'));
  } catch {
    // No scenes dir yet — generate empty registry
  }

  const imports: string[] = [];
  const registryEntries: string[] = [];

  for (const file of sceneFiles) {
    const name = basename(file, file.endsWith('.tsx') ? '.tsx' : '.ts');
    const varName = name.replace(/[^a-zA-Z0-9_]/g, '_');
    // Use wildcard import — scenes may export default or named
    imports.push(`import * as ${varName}_mod from './scenes/${name}';`);
    // Key is filename (e.g. 'HookTitle.tsx') — matches data.sceneFile in manifest
    // Prefer default export, then named export matching filename, then first exported component
    // The helper function finds the first React component export regardless of name
    registryEntries.push(`  '${file}': (${varName}_mod.default || ${varName}_mod.${varName} || Object.values(${varName}_mod).find(v => typeof v === 'function')) as React.ComponentType<any>,`);
  }

  const code = `// AUTO-GENERATED by scene-registry-generator — do not edit
import React from 'react';
${imports.join('\n')}

export const sceneRegistry: Record<string, React.ComponentType<any>> = {
${registryEntries.join('\n')}
};
`;

  await writeFile(REGISTRY_FILE, code);
  logger.info({ count: sceneFiles.length }, 'Scene registry generated');
}
