import { readdir, writeFile } from 'fs/promises';
import { join, basename } from 'path';
import pino from 'pino';

const logger = pino({ name: 'scene-registry' });

const SCENES_DIR = '/workspace/src/scenes';
const REGISTRY_FILE = '/workspace/src/scene-registry.ts';

export async function generateSceneRegistry(): Promise<void> {
  let sceneFiles: string[] = [];

  try {
    const entries = await readdir(SCENES_DIR);
    // Pick up Scene*.tsx files (SceneN.tsx, SceneNBehind.tsx, SceneNFront.tsx)
    sceneFiles = entries.filter(f => /^Scene\d+\w*\.tsx$/.test(f));
  } catch {
    // No scenes dir yet — generate empty registry
  }

  const imports: string[] = [];
  const registryEntries: string[] = [];

  for (const file of sceneFiles) {
    const name = basename(file, file.endsWith('.tsx') ? '.tsx' : '.ts');
    const varName = name.replace(/[^a-zA-Z0-9_]/g, '_');
    imports.push(`import ${varName}_default from './scenes/${name}';`);
    // Key is filename (e.g. 'HookTitle.tsx') — matches data.sceneFile in manifest
    registryEntries.push(`  '${file}': ${varName}_default,`);
  }

  const code = `// AUTO-GENERATED by scene-registry-generator — do not edit
import React from 'react';
${imports.join('\n')}

export const sceneRegistry: Record<string, React.ComponentType<any>> = {
${registryEntries.join('\n')}
};
`;

  await writeFile(REGISTRY_FILE, code);
  logger.info({ count: sceneFiles.length }, 'Scene registry generated');
}
