import { mkdir, writeFile, cp, access, symlink, readlink } from 'fs/promises';
import { createWriteStream } from 'fs';
import { join } from 'path';
import { pipeline } from 'stream/promises';
import { Client as MinioClient } from 'minio';
import pino from 'pino';

const logger = pino({ name: 'workspace-init' });

const WORKSPACE = '/workspace';
const TEMPLATE = '/app/template';
const NODE_MODULES_SRC = '/app/node_modules';

interface InitPayload {
  videoUrl: string;      // MinIO key for source video
  audioUrl?: string;     // MinIO key for separate audio (optional)
  manifest: object;      // Initial manifest from DB
}

function getMinioClient(): MinioClient {
  return new MinioClient({
    endPoint: process.env.MINIO_ENDPOINT || 'localhost',
    port: parseInt(process.env.MINIO_PORT || '9000', 10),
    useSSL: process.env.MINIO_USE_SSL === 'true',
    accessKey: process.env.MINIO_ACCESS_KEY || '',
    secretKey: process.env.MINIO_SECRET_KEY || '',
  });
}

/**
 * Check if workspace is already initialized (volume was restored from backup).
 */
export async function isInitialized(): Promise<boolean> {
  try {
    await access(join(WORKSPACE, 'manifest.json'));
    return true;
  } catch {
    return false;
  }
}

/**
 * Initialize workspace on first boot.
 * Downloads video, writes manifest, copies template files.
 */
export async function initWorkspace(payload: InitPayload): Promise<void> {
  logger.info('Initializing workspace (first boot)');

  // Create directory structure
  await mkdir(join(WORKSPACE, 'src', 'segments'), { recursive: true });
  await mkdir(join(WORKSPACE, 'src', 'components'), { recursive: true });
  await mkdir(join(WORKSPACE, 'public'), { recursive: true });
  await mkdir(join(WORKSPACE, '.build'), { recursive: true });
  await mkdir(join(WORKSPACE, '.claude'), { recursive: true });

  // Download video from MinIO
  const minio = getMinioClient();
  const bucket = process.env.MINIO_BUCKET || 'viona';

  logger.info({ key: payload.videoUrl }, 'Downloading source video');
  const videoStream = await minio.getObject(bucket, payload.videoUrl);
  await pipeline(videoStream, createWriteStream(join(WORKSPACE, 'public', 'source.mp4')));
  logger.info('Video downloaded');

  // Download audio if separate
  if (payload.audioUrl) {
    logger.info({ key: payload.audioUrl }, 'Downloading audio');
    const audioStream = await minio.getObject(bucket, payload.audioUrl);
    await pipeline(audioStream, createWriteStream(join(WORKSPACE, 'public', 'audio.mp3')));
  }

  // Write manifest
  await writeFile(
    join(WORKSPACE, 'manifest.json'),
    JSON.stringify(payload.manifest, null, 2),
  );

  // Copy template files (composition infra, .claude/, configs)
  await cp(TEMPLATE, WORKSPACE, {
    recursive: true,
    force: false,  // Don't overwrite existing files
  });

  // Generate PlayerComposition.tsx — the esbuild entry point.
  // Without this file, esbuild has nothing to bundle on first boot.
  await writeFile(
    join(WORKSPACE, 'src', 'PlayerComposition.tsx'),
    [
      'import React from "react";',
      'import { AbsoluteFill } from "remotion";',
      '',
      '// Auto-generated entry point for esbuild CJS bundle.',
      '// Will be regenerated by codegen after AI generates visuals.',
      'export const PlayerComposition: React.FC = () => {',
      '  return <AbsoluteFill style={{ backgroundColor: "#000" }} />;',
      '};',
      '',
    ].join('\n'),
  );

  logger.info('Workspace initialized');
}

/**
 * Ensure node_modules symlink exists. Runs on every boot (first boot + resume).
 */
export async function ensureNodeModulesSymlink(): Promise<void> {
  const target = join(WORKSPACE, 'node_modules');

  try {
    const existing = await readlink(target);
    if (existing === NODE_MODULES_SRC) return; // Already correct
  } catch {
    // Doesn't exist or not a symlink — create it
  }

  try {
    await symlink(NODE_MODULES_SRC, target, 'junction');
    logger.info('node_modules symlinked');
  } catch (err: any) {
    if (err.code !== 'EEXIST') throw err;
  }
}
