import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { TransformWrapper } from './composition/TransformWrapper';
import { VideoItem, AudioItem, TextItem, ImageItem, SceneItem, ShapeItem, CaptionItem } from './items';
// Scene registry — auto-generated by esbuild watcher before each build.
// File is guaranteed to exist (workspace-init creates empty stub, generator updates before each build).
import { sceneRegistry } from './scene-registry';

interface ManifestItem {
  id: string;
  type: string;
  trackId: string;
  startMs: number;
  endMs: number;
  data: any;
  transform?: any;
  keyframes?: any[];
  filters?: any;
}

interface ManifestTrack {
  id: string;
  type: string;
  name: string;
  position: number;
}

interface Manifest {
  version: number;
  fps: number;
  durationMs: number;
  canvas: { width: number; height: number };
  tracks: ManifestTrack[];
  items: ManifestItem[];
  assets: Record<string, string>;
  captionStyle?: any;
}

interface PlayerCompositionProps {
  manifest: Manifest;
}

export const PlayerComposition: React.FC<PlayerCompositionProps> = ({ manifest }) => {
  const { fps, canvas, tracks, items, assets, captionStyle } = manifest;
  const sortedTracks = [...tracks].sort((a, b) => a.position - b.position);

  return (
    <AbsoluteFill style={{ backgroundColor: '#000' }}>
      {sortedTracks.map(track => {
        const trackItems = items.filter(item => item.trackId === track.id);
        if (trackItems.length === 0) return null;

        return (
          <AbsoluteFill key={track.id}>
            {trackItems.map(item => {
              const startFrame = Math.round((item.startMs / 1000) * fps);
              const durationInFrames = Math.max(1, Math.round(((item.endMs - item.startMs) / 1000) * fps));

              return (
                <Sequence
                  key={item.id}
                  from={startFrame}
                  durationInFrames={durationInFrames}
                  layout="none"
                >
                  {item.transform ? (
                    <TransformWrapper
                      transform={item.transform}
                      keyframes={item.keyframes}
                      filters={item.filters}
                      fps={fps}
                    >
                      <ItemRenderer
                        item={item}
                        assets={assets}
                        fps={fps}
                        durationInFrames={durationInFrames}
                        canvas={canvas}
                        captionStyle={captionStyle}
                      />
                    </TransformWrapper>
                  ) : (
                    <ItemRenderer
                      item={item}
                      assets={assets}
                      fps={fps}
                      durationInFrames={durationInFrames}
                      canvas={canvas}
                      captionStyle={captionStyle}
                    />
                  )}
                </Sequence>
              );
            })}
          </AbsoluteFill>
        );
      })}
    </AbsoluteFill>
  );
};

interface ItemRendererProps {
  item: ManifestItem;
  assets: Record<string, string>;
  fps: number;
  durationInFrames: number;
  canvas: { width: number; height: number };
  captionStyle?: any;
}

const ItemRenderer: React.FC<ItemRendererProps> = ({
  item,
  assets,
  fps,
  durationInFrames,
  canvas,
  captionStyle,
}) => {
  switch (item.type) {
    case 'video':
      return <VideoItem data={item.data} assets={assets} fps={fps} durationInFrames={durationInFrames} />;
    case 'audio':
      return <AudioItem data={item.data} assets={assets} fps={fps} />;
    case 'text':
      return <TextItem data={item.data} />;
    case 'image':
      return <ImageItem data={item.data} assets={assets} />;
    case 'scene':
      return (
        <SceneItem
          data={item.data}
          width={canvas.width}
          height={canvas.height}
          durationInFrames={durationInFrames}
          fps={fps}
          sceneRegistry={sceneRegistry}
        />
      );
    case 'shape':
      return <ShapeItem data={item.data} />;
    case 'caption':
      return <CaptionItem data={item.data} captionStyle={captionStyle || {}} fps={fps} itemStartMs={item.startMs} />;
    default:
      return null;
  }
};
