#!/usr/bin/env python3
"""
Full Pipeline Test - End-to-End Agent Tests with Real API

This test runs the actual visual_generator.py with real API calls.
Logs are saved to /output/logs/ for analysis.

Usage (from Docker):
    docker run --rm \
        -e GEMINI_API_KEY=$GEMINI_API_KEY \
        -v /path/to/output:/output \
        --entrypoint python3 \
        clipify-openhands-sandbox \
        /opt/openhands/tests/test_full_pipeline.py

Run: python /opt/openhands/tests/test_full_pipeline.py
"""

import json
import os
import subprocess
import sys
from pathlib import Path

# Colors for output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
RESET = "\033[0m"

WORKSPACE = os.environ.get("REMOTION_PROJECT_DIR", "/opt/remotion-template")
PROJECT_ID = "proj_test_mock"
# Remotion composition ID (underscores converted to hyphens)
COMPOSITION_ID = PROJECT_ID.replace('_', '-')


def log(msg: str, color: str = ""):
    print(f"{color}{msg}{RESET}")


def log_step(step: int, msg: str):
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}Step {step}: {msg}{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")


def run_cmd(cmd: str, cwd: str = WORKSPACE) -> tuple[int, str, str]:
    """Run a shell command and return exit_code, stdout, stderr."""
    result = subprocess.run(
        cmd,
        shell=True,
        cwd=cwd,
        capture_output=True,
        text=True
    )
    return result.returncode, result.stdout, result.stderr


def create_mock_component():
    """Create a mock visual component that looks like what the agent would generate."""
    log_step(1, "Creating Mock Visual Component")

    project_dir = Path(WORKSPACE) / "src" / PROJECT_ID
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create the main composition component
    component_code = '''import React from 'react';
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
  Sequence,
} from 'remotion';

// Animated title component
const AnimatedTitle: React.FC<{ text: string; delay: number }> = ({ text, delay }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const opacity = interpolate(frame, [delay, delay + 20], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  const scale = spring({
    frame: frame - delay,
    fps,
    config: { damping: 12, stiffness: 100 },
  });

  const translateY = interpolate(frame, [delay, delay + 30], [50, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <div
      style={{
        opacity,
        transform: `scale(${scale}) translateY(${translateY}px)`,
        fontSize: 72,
        fontWeight: 700,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Roboto, sans-serif',
      }}
    >
      {text}
    </div>
  );
};

// Progress bar component
const ProgressBar: React.FC = () => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  const progress = interpolate(frame, [0, durationInFrames], [0, 100]);

  return (
    <div
      style={{
        position: 'absolute',
        bottom: 40,
        left: '10%',
        width: '80%',
        height: 6,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 3,
      }}
    >
      <div
        style={{
          width: `${progress}%`,
          height: '100%',
          backgroundColor: '#4f46e5',
          borderRadius: 3,
        }}
      />
    </div>
  );
};

// Main composition
export const TestMockVisual: React.FC = () => {
  const frame = useCurrentFrame();

  // Background gradient animation
  const hue = interpolate(frame, [0, 150], [220, 280], {
    extrapolateRight: 'clamp',
  });

  const title = 'Hello World';
  const subtitle = 'Generated by Clipify';

  return (
    <AbsoluteFill
      style={{
        background: `linear-gradient(135deg, hsl(${hue}, 60%, 10%) 0%, hsl(${hue + 30}, 50%, 15%) 100%)`,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      {/* Scene 1: Title animation */}
      <Sequence from={0} durationInFrames={60}>
        <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center' }}>
          <AnimatedTitle text={title} delay={0} />
        </AbsoluteFill>
      </Sequence>

      {/* Scene 2: Subtitle */}
      <Sequence from={30} durationInFrames={120}>
        <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center', paddingTop: 100 }}>
          <div
            style={{
              fontSize: 32,
              color: 'rgba(255,255,255,0.7)',
              fontFamily: 'Open Sans, sans-serif',
            }}
          >
            {subtitle}
          </div>
        </AbsoluteFill>
      </Sequence>

      {/* Progress bar */}
      <ProgressBar />
    </AbsoluteFill>
  );
};

// Default export for composition registration
export default TestMockVisual;
'''

    index_file = project_dir / "index.tsx"
    index_file.write_text(component_code)
    log(f"  Created: {index_file}", GREEN)

    # Create metadata.json
    metadata = {
        "compositionId": PROJECT_ID,
        "durationInFrames": 150,
        "fps": 30,
        "width": 1920,
        "height": 1080,
        "visuals": [
            {"startMs": 0, "endMs": 2000, "type": "title", "description": "Animated title"},
            {"startMs": 1000, "endMs": 5000, "type": "subtitle", "description": "Subtitle fade in"},
        ]
    }

    metadata_file = project_dir / "metadata.json"
    metadata_file.write_text(json.dumps(metadata, indent=2))
    log(f"  Created: {metadata_file}", GREEN)

    return True


def generate_root():
    """Use root_generator to create Root.tsx."""
    log_step(2, "Generating Root.tsx")

    sys.path.insert(0, "/opt/openhands")
    from tools.root_generator import generate_and_write_root

    success, message, compositions = generate_and_write_root(WORKSPACE, PROJECT_ID)

    if success:
        log(f"  {message}", GREEN)
        for comp in compositions:
            log(f"    - {comp.composition_id} ({comp.component_name})", GREEN)
    else:
        log(f"  Failed: {message}", RED)

    return success


def run_typescript_validation():
    """Run TypeScript compiler to check for errors."""
    log_step(3, "TypeScript Validation")

    exit_code, stdout, stderr = run_cmd("npx tsc --noEmit")

    if exit_code == 0:
        log("  TypeScript validation PASSED", GREEN)
        return True, []
    else:
        log("  TypeScript validation FAILED", RED)
        errors = []
        output = stdout + stderr
        for line in output.split('\n'):
            if 'error TS' in line:
                errors.append(line.strip())
                log(f"    {line.strip()}", RED)
        return False, errors


def run_bundle():
    """Bundle the Remotion project."""
    log_step(4, "Remotion Bundle")

    exit_code, stdout, stderr = run_cmd(
        "npx remotion bundle src/index.tsx --out-dir=build --log=error"
    )

    output = stdout + stderr

    # Check if bundle was created
    bundle_exists = Path(WORKSPACE) / "build" / "index.html"

    if bundle_exists.exists():
        log("  Bundle created successfully", GREEN)

        # List bundle contents
        exit_code2, files, _ = run_cmd("ls -la build/")
        log(f"  Bundle contents:", BLUE)
        for line in files.strip().split('\n')[:5]:
            log(f"    {line}")

        return True, []
    else:
        log("  Bundle FAILED", RED)
        errors = [line for line in output.split('\n') if 'error' in line.lower()]
        for e in errors[:5]:
            log(f"    {e}", RED)
        return False, errors


def render_screenshots():
    """Render screenshots at different frames."""
    log_step(5, "Rendering Screenshots")

    frames_to_render = [0, 45, 120]  # Start, middle, near-end
    screenshots = []

    for frame in frames_to_render:
        output_path = f"/tmp/frame_{frame}.png"

        cmd = f"npx remotion still src/index.tsx {COMPOSITION_ID} {output_path} --frame={frame}"
        exit_code, stdout, stderr = run_cmd(cmd)

        if Path(output_path).exists():
            file_size = Path(output_path).stat().st_size
            log(f"  Frame {frame}: OK ({file_size / 1024:.1f} KB)", GREEN)
            screenshots.append({"frame": frame, "path": output_path, "size": file_size})
        else:
            log(f"  Frame {frame}: FAILED", RED)
            output = stdout + stderr
            if output.strip():
                log(f"    {output[:200]}", YELLOW)

    return len(screenshots) == len(frames_to_render), screenshots


def calculate_score(ts_passed: bool, ts_errors: list, bundle_passed: bool, screenshots: list):
    """Calculate a mock score based on test results."""
    log_step(6, "Calculating Score")

    # Scoring weights (matching the 70/10/10/10 system)
    score = 0
    breakdown = {
        "visualQuality": 0,
        "correctness": 0,
        "completeness": 0,
        "codeQuality": 0,
    }
    issues = []

    # Correctness (10 points) - TypeScript compiles
    if ts_passed:
        breakdown["correctness"] = 10
        log("  Correctness: 10/10 (TypeScript passed)", GREEN)
    else:
        breakdown["correctness"] = 0
        issues.append(f"TypeScript errors: {len(ts_errors)}")
        log(f"  Correctness: 0/10 (TypeScript failed with {len(ts_errors)} errors)", RED)

    # Completeness (10 points) - All files present, bundle works
    if bundle_passed:
        breakdown["completeness"] = 10
        log("  Completeness: 10/10 (Bundle successful)", GREEN)
    else:
        breakdown["completeness"] = 5
        issues.append("Bundle failed")
        log("  Completeness: 5/10 (Bundle failed)", YELLOW)

    # Visual Quality (70 points) - Screenshots render
    if len(screenshots) == 3:
        # All screenshots rendered - check sizes (non-empty images)
        valid_screenshots = [s for s in screenshots if s["size"] > 10000]  # >10KB
        if len(valid_screenshots) == 3:
            breakdown["visualQuality"] = 65  # Good but not perfect (no actual visual review)
            log("  Visual Quality: 65/70 (All frames rendered)", GREEN)
        else:
            breakdown["visualQuality"] = 40
            issues.append("Some screenshots may be blank")
            log("  Visual Quality: 40/70 (Some frames may be blank)", YELLOW)
    elif len(screenshots) > 0:
        breakdown["visualQuality"] = 30
        issues.append(f"Only {len(screenshots)}/3 screenshots rendered")
        log(f"  Visual Quality: 30/70 (Only {len(screenshots)}/3 frames)", YELLOW)
    else:
        breakdown["visualQuality"] = 0
        issues.append("No screenshots could be rendered")
        log("  Visual Quality: 0/70 (No screenshots)", RED)

    # Code Quality (10 points) - Check for best practices
    # In a real scenario, this would analyze the code
    breakdown["codeQuality"] = 8  # Assume decent quality for mock
    log("  Code Quality: 8/10 (Mock assessment)", GREEN)

    # Calculate total
    score = sum(breakdown.values())

    return {
        "score": score,
        "breakdown": breakdown,
        "issues": issues,
        "suggestion": "This is a mock test. Real scoring would involve visual inspection."
    }


def main():
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  CLIPIFY VISUAL GENERATION - FULL PIPELINE TEST{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    results = {
        "component_created": False,
        "root_generated": False,
        "typescript_passed": False,
        "bundle_passed": False,
        "screenshots_passed": False,
        "score": None,
    }

    # Step 1: Create mock component
    results["component_created"] = create_mock_component()
    if not results["component_created"]:
        log("\nPipeline FAILED at component creation", RED)
        return 1

    # Step 2: Generate Root.tsx
    results["root_generated"] = generate_root()
    if not results["root_generated"]:
        log("\nPipeline FAILED at Root.tsx generation", RED)
        return 1

    # Step 3: TypeScript validation
    ts_passed, ts_errors = run_typescript_validation()
    results["typescript_passed"] = ts_passed

    # Step 4: Bundle (even if TS fails, try bundling)
    bundle_passed, bundle_errors = run_bundle()
    results["bundle_passed"] = bundle_passed

    # Step 5: Screenshots
    screenshots_passed, screenshots = render_screenshots()
    results["screenshots_passed"] = screenshots_passed

    # Step 6: Calculate score
    score_result = calculate_score(ts_passed, ts_errors, bundle_passed, screenshots)
    results["score"] = score_result

    # Final summary
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  FINAL RESULTS{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    print(f"\n  Component Created:  {'✓' if results['component_created'] else '✗'}")
    print(f"  Root Generated:     {'✓' if results['root_generated'] else '✗'}")
    print(f"  TypeScript Passed:  {'✓' if results['typescript_passed'] else '✗'}")
    print(f"  Bundle Passed:      {'✓' if results['bundle_passed'] else '✗'}")
    print(f"  Screenshots Passed: {'✓' if results['screenshots_passed'] else '✗'}")

    print(f"\n{BLUE}  SCORE: {score_result['score']}/100{RESET}")
    print(f"  Breakdown:")
    for key, value in score_result["breakdown"].items():
        max_val = 70 if key == "visualQuality" else 10
        print(f"    - {key}: {value}/{max_val}")

    if score_result["issues"]:
        print(f"\n  Issues:")
        for issue in score_result["issues"]:
            print(f"    - {issue}")

    # Determine pass/fail
    threshold = 90
    if score_result["score"] >= threshold:
        print(f"\n{GREEN}  PASSED (score >= {threshold}){RESET}")
        return 0
    else:
        print(f"\n{YELLOW}  BELOW THRESHOLD (score < {threshold}){RESET}")
        return 0  # Still return 0 for test purposes


def run_real_agent_test(test_name: str, prompt: str, project_id: str, max_iterations: int = 1, model: str = "gemini-2.0-flash"):
    """Run actual visual_generator.py with real API calls."""
    import time

    log_step(0, f"REAL AGENT TEST: {test_name}")

    # Ensure output/logs directory exists
    log_dir = Path("/output/logs")
    log_dir.mkdir(parents=True, exist_ok=True)

    output_dir = Path("/output") / test_name
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write prompt file
    prompt_file = Path(f"/tmp/{test_name}_prompt.json")
    prompt_file.write_text(json.dumps({"prompt": prompt}))

    log_file = log_dir / f"{test_name}.log"

    # Build command
    cmd = [
        "python3", "/opt/openhands/visual_generator.py",
        "--workspace", WORKSPACE,
        "--project-id", project_id,
        "--model", model,
        "--prompt-file", str(prompt_file),
        "--output-dir", str(output_dir),
        "--max-iterations", str(max_iterations),
        "--duration-frames", "150",
        "--fps", "30",
    ]

    log(f"  Command: {' '.join(cmd[:5])}...", BLUE)
    log(f"  Log file: {log_file}", BLUE)

    start_time = time.time()

    try:
        with open(log_file, 'w') as log_f:
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env={**os.environ, "PYTHONUNBUFFERED": "1"},
            )

            # Stream output to both console and log file
            events = []
            for line in process.stdout:
                log_f.write(line)
                log_f.flush()

                # Parse JSON events
                line = line.strip()
                if line.startswith('{'):
                    try:
                        event = json.loads(line)
                        events.append(event)
                        event_type = event.get('type', 'unknown')

                        # Print important events
                        if event_type == 'error':
                            log(f"  ERROR: {event.get('message', 'Unknown')[:100]}", RED)
                        elif event_type == 'complete':
                            log(f"  COMPLETE: score={event.get('final_score', 0)}, status={event.get('status', 'unknown')}", GREEN)
                        elif event_type == 'iteration_complete':
                            log(f"  Iteration {event.get('iteration')}: score={event.get('score', 0)}", YELLOW)
                        elif event_type == 'tool_result' and not event.get('success'):
                            log(f"  Tool failed: {event.get('tool')} - {event.get('error', 'unknown')[:80]}", RED)
                    except json.JSONDecodeError:
                        pass
                elif 'error' in line.lower() or 'Error' in line:
                    log(f"  {line[:100]}", YELLOW)

            process.wait(timeout=300)
            return_code = process.returncode

    except subprocess.TimeoutExpired:
        process.kill()
        log("  TIMEOUT after 300s", RED)
        return_code = -1
        events = []
    except Exception as e:
        log(f"  Exception: {e}", RED)
        return_code = -1
        events = []

    duration = time.time() - start_time

    # Check output files
    output_files = list(output_dir.rglob("*.*"))

    # Extract final result from events
    final_score = 0
    status = "failed"
    errors = []

    for event in events:
        if event.get('type') == 'complete':
            final_score = event.get('final_score', 0)
            status = event.get('status', 'unknown')
        elif event.get('type') == 'error':
            errors.append(event.get('message', 'Unknown error'))

    result = {
        "test_name": test_name,
        "project_id": project_id,
        "duration_seconds": round(duration, 1),
        "return_code": return_code,
        "final_score": final_score,
        "status": status,
        "output_files": [str(f.relative_to(output_dir)) for f in output_files],
        "errors": errors,
        "log_file": str(log_file),
    }

    # Save result JSON
    result_file = log_dir / f"{test_name}_result.json"
    result_file.write_text(json.dumps(result, indent=2))

    # Print summary
    success = return_code == 0 and len(output_files) > 0
    status_str = f"{GREEN}PASS{RESET}" if success else f"{RED}FAIL{RESET}"
    log(f"\n  Result: {status_str} (score={final_score}, files={len(output_files)}, duration={duration:.0f}s)")

    return result


def run_all_real_tests():
    """Run all real agent tests with actual API calls."""
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  END-TO-END AGENT TESTS WITH REAL API{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    # Check API key
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        log("ERROR: GEMINI_API_KEY not set", RED)
        return 1

    log(f"API Key: {'*' * 20}...{api_key[-4:]}", GREEN)

    # Define tests
    tests = [
        {
            "name": "test_hello_world",
            "prompt": "Create a simple animation showing 'Hello World' text fading in on a dark blue (#001133) background. Use large white centered text (100px). The text should fade in from 0 to 1 opacity over 30 frames.",
            "project_id": "test_hello_world",
        },
        {
            "name": "test_counter",
            "prompt": "Create an animated counter that displays numbers 1 through 5. Each number should fade in, stay visible for 30 frames, then fade out. Use large white text (150px) centered on a dark purple gradient background.",
            "project_id": "test_counter",
        },
        {
            "name": "test_bar_chart",
            "prompt": "Create an animated horizontal bar chart with 3 bars: 'Sales' (70%), 'Marketing' (50%), 'Engineering' (85%). Each bar should animate from 0 to full width using spring animation. Use a dark theme with colorful bars.",
            "project_id": "test_bar_chart",
        },
    ]

    results = []

    for test in tests:
        # Reset workspace before each test
        src_dir = Path(WORKSPACE) / "src"
        for item in src_dir.iterdir():
            if item.is_dir() and item.name.startswith("test_"):
                import shutil
                shutil.rmtree(item)

        # Reset Root.tsx
        root_tsx = src_dir / "Root.tsx"
        root_tsx.write_text('''import "./index.css";
import React from "react";
import { Composition } from "remotion";

const Placeholder: React.FC = () => (
  <div style={{ backgroundColor: '#1a1a2e', width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
    <span style={{ color: '#fff', fontSize: 32 }}>Waiting for composition...</span>
  </div>
);

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="placeholder"
      component={Placeholder}
      durationInFrames={30}
      fps={30}
      width={1920}
      height={1080}
    />
  );
};
''')

        result = run_real_agent_test(
            test_name=test["name"],
            prompt=test["prompt"],
            project_id=test["project_id"],
            max_iterations=1,
        )
        results.append(result)

    # Summary
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  TEST SUMMARY{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    passed = sum(1 for r in results if r["return_code"] == 0 and len(r["output_files"]) > 0)
    failed = len(results) - passed

    for r in results:
        status = "✓" if r["return_code"] == 0 and len(r["output_files"]) > 0 else "✗"
        print(f"  {status} {r['test_name']}: score={r['final_score']}, files={len(r['output_files'])}, {r['duration_seconds']}s")
        if r["errors"]:
            for err in r["errors"][:2]:
                print(f"      Error: {err[:80]}")

    print(f"\n  Passed: {passed}/{len(results)}")
    print(f"  Failed: {failed}/{len(results)}")

    # Save summary
    summary_file = Path("/output/logs/summary.json")
    summary_file.write_text(json.dumps({
        "passed": passed,
        "failed": failed,
        "total": len(results),
        "results": results,
    }, indent=2))

    print(f"\n  Logs saved to: /output/logs/")
    print(f"  Summary: {summary_file}")

    return 0 if failed == 0 else 1


def run_openrouter_test(model_name: str, test_name: str = None):
    """Run a single test with a specific OpenRouter model."""
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  OPENROUTER MODEL TEST: {model_name}{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    # Check API key
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        log("ERROR: OPENROUTER_API_KEY not set", RED)
        return 1

    log(f"API Key: {'*' * 20}...{api_key[-4:]}", GREEN)
    log(f"Model: {model_name}", BLUE)

    # Clean project name from model
    if not test_name:
        test_name = "test_" + model_name.replace("/", "_").replace(":", "_").replace("-", "_")[:30]

    project_id = test_name

    # Reset workspace
    src_dir = Path(WORKSPACE) / "src"
    for item in src_dir.iterdir():
        if item.is_dir() and item.name.startswith("test_"):
            import shutil
            shutil.rmtree(item)

    # Reset Root.tsx
    root_tsx = src_dir / "Root.tsx"
    root_tsx.write_text('''import "./index.css";
import React from "react";
import { Composition } from "remotion";

const Placeholder: React.FC = () => (
  <div style={{ backgroundColor: '#1a1a2e', width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
    <span style={{ color: '#fff', fontSize: 32 }}>Waiting for composition...</span>
  </div>
);

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="placeholder"
      component={Placeholder}
      durationInFrames={30}
      fps={30}
      width={1920}
      height={1080}
    />
  );
};
''')

    result = run_real_agent_test(
        test_name=test_name,
        prompt="Create a simple animation showing 'Hello World' text fading in on a dark blue (#001133) background. Use large white centered text (100px). The text should fade in from 0 to 1 opacity over 30 frames.",
        project_id=project_id,
        max_iterations=3,  # Allow self-healing iterations
        model=f"openrouter/{model_name}",
    )

    # Print detailed result
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}  RESULT{RESET}")
    print(f"{BLUE}{'='*60}{RESET}")

    status = "PASS" if result["return_code"] == 0 and len(result["output_files"]) > 0 else "FAIL"
    status_color = GREEN if status == "PASS" else RED

    print(f"  Status: {status_color}{status}{RESET}")
    print(f"  Score: {result['final_score']}")
    print(f"  Duration: {result['duration_seconds']}s")
    print(f"  Output files: {len(result['output_files'])}")
    print(f"  Log: {result['log_file']}")

    if result["errors"]:
        print(f"\n  Errors:")
        for err in result["errors"]:
            print(f"    - {err[:100]}")

    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    # Check for specific model argument
    if len(sys.argv) > 1:
        model_arg = sys.argv[1]
        # If it looks like an OpenRouter model, run OpenRouter test
        if "/" in model_arg or "openrouter" in model_arg.lower():
            model_name = model_arg.replace("openrouter/", "")
            sys.exit(run_openrouter_test(model_name))

    # Check if we should run real tests or mock tests
    if os.environ.get("GEMINI_API_KEY") and os.path.exists("/output"):
        # Run real end-to-end tests
        sys.exit(run_all_real_tests())
    elif os.environ.get("OPENROUTER_API_KEY") and os.path.exists("/output"):
        # Run with OpenRouter if only OpenRouter key is available
        # tngtech/tng-r1t-chimera:free is verified to support tool calling
        sys.exit(run_openrouter_test("tngtech/tng-r1t-chimera:free"))
    else:
        # Run mock tests (original behavior)
        sys.exit(main())
