import { Job } from 'bullmq';
import { eq } from 'drizzle-orm';
import { existsSync } from 'fs';
import { mkdir, rm, readFile, writeFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { tmpdir } from 'os';
import { nanoid } from 'nanoid';
import { db, jobs } from '../db/index.js';
import { downloadFile, uploadFile } from '../services/minio.js';
import { logger } from '../logger.js';
import { publishJobProgress, publishJobComplete, publishJobError } from '../services/redis.js';
import { config } from '../config.js';
import { runSubprocess } from '../utils/subprocess.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export interface SegmentationJobData {
  projectId: string;
  jobId: string;
  videoKey: string;
  startMs: number;
  endMs: number;
  sceneId: string;
  outputKey: string;
  callbackUrl?: string;
  callbackSecret?: string;
}

export async function processSegmentationJob(job: Job<SegmentationJobData>) {
  const { projectId, jobId, videoKey, startMs, endMs, sceneId, outputKey, callbackUrl, callbackSecret } = job.data;
  const workDir = join(tmpdir(), `viona-segment-${nanoid()}`);

  try {
    await mkdir(workDir, { recursive: true });

    // Update job status
    await db.update(jobs)
      .set({ status: 'processing', progress: 0 })
      .where(eq(jobs.id, jobId));

    const pubExtras = { projectId, sceneId };

    // Step 1: Download source video (10%)
    await publishJobProgress(jobId, 5, 'Downloading video for segmentation...', pubExtras);
    const videoPath = join(workDir, 'source.mp4');
    await downloadFile('uploads', videoKey, videoPath);
    await publishJobProgress(jobId, 10, 'Video downloaded', pubExtras);

    // Step 2: Run segment_person.py on the FULL video (10-80%)
    // No clipping — processes the entire video at native frame rate for:
    //   1. Exact 1:1 frame correspondence with source (no seeking/resampling)
    //   2. Best RVM quality (recurrent state builds up continuously)
    //   3. Same frame rate as source (no 29.97→30 drift)
    await publishJobProgress(jobId, 12, 'Running person segmentation (full video)...', pubExtras);

    const mattePath = join(workDir, 'matte.mp4');
    const bgPath = join(workDir, `bg-${sceneId}.png`);

    // Resolve script path (same pattern as head-tracking.ts)
    // In prod (tsup bundle): __dirname = .../dist → one level up
    // In dev (tsx):           __dirname = .../src/processors → two levels up
    let resolvedScriptPath = join(__dirname, '..', 'scripts', 'segment_person.py');
    if (!existsSync(resolvedScriptPath)) {
      resolvedScriptPath = join(__dirname, '..', '..', 'scripts', 'segment_person.py');
    }

    await runSegmentation(
      videoPath,
      mattePath,
      resolvedScriptPath,
      jobId,
      projectId,
      sceneId,
      startMs,
      endMs,
      bgPath,
    );

    await publishJobProgress(jobId, 80, 'Segmentation complete', pubExtras);

    // Step 4: Upload matte + bbox to MinIO (90%)
    await publishJobProgress(jobId, 85, 'Uploading matte...', pubExtras);
    await uploadFile('outputs', outputKey, mattePath);

    // Upload matte-bbox.json (written by segment_person.py alongside the matte)
    // Full video matte: sourceStartMs is always 0 (no clipping)
    const bboxPath = join(workDir, 'matte-bbox.json');
    const bboxKey = outputKey.replace(/\.mp4$/, '-bbox.json');
    if (existsSync(bboxPath)) {
      const bboxData = JSON.parse(await readFile(bboxPath, 'utf-8'));
      bboxData.sourceStartMs = 0;
      await writeFile(bboxPath, JSON.stringify(bboxData));
      await uploadFile('outputs', bboxKey, bboxPath);
      logger.info({ projectId, sceneId, bboxKey }, 'Matte bbox uploaded');
    }

    // Upload foreground video (written by segment_person.py alongside the matte)
    const fgrPath = mattePath.replace(/\.mp4$/, '-fgr.mp4');
    const fgrKey = outputKey.replace(/\.mp4$/, '-fgr.mp4');
    if (existsSync(fgrPath)) {
      await uploadFile('outputs', fgrKey, fgrPath);
      logger.info({ projectId, sceneId, fgrKey }, 'Foreground video uploaded');
    }

    // Upload background image (generated by segment_person.py via OpenAI)
    const bgKey = `projects/${projectId}/bg-${sceneId}.png`;
    if (existsSync(bgPath)) {
      await uploadFile('outputs', bgKey, bgPath);
      logger.info({ projectId, sceneId, bgKey }, 'Background image uploaded');
    }

    await publishJobProgress(jobId, 90, 'Matte uploaded', pubExtras);

    // Step 5: Notify sandbox via callback if provided
    if (callbackUrl) {
      try {
        await fetch(callbackUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...(callbackSecret ? { 'Authorization': `Bearer ${callbackSecret}` } : {}),
          },
          body: JSON.stringify({
            type: 'segmentation_complete',
            sceneId,
            outputKey,
            bboxKey,
            fgrKey,
            bgKey: existsSync(bgPath) ? bgKey : undefined,
            jobId,
          }),
        });
        logger.info({ projectId, sceneId, jobId }, 'Segmentation callback sent');
      } catch (err) {
        logger.warn({ err, projectId, sceneId }, 'Segmentation callback failed (non-critical)');
      }
    }

    // Step 6: Complete
    await db.update(jobs)
      .set({ status: 'complete', progress: 100, completedAt: new Date() })
      .where(eq(jobs.id, jobId));

    await publishJobProgress(jobId, 100, 'Complete', pubExtras);
    await publishJobComplete(jobId, projectId);

    logger.info({ projectId, sceneId }, 'Segmentation complete');

  } catch (error) {
    logger.error({ projectId, sceneId, err: error }, 'Segmentation failed');

    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    await db.update(jobs)
      .set({ status: 'failed', error: errorMessage })
      .where(eq(jobs.id, jobId));

    await publishJobError(jobId, errorMessage, { projectId });

    throw error;
  } finally {
    try {
      await rm(workDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  }
}

async function runSegmentation(
  videoPath: string,
  mattePath: string,
  scriptPath: string,
  jobId: string,
  projectId: string,
  sceneId: string,
  startMs: number,
  endMs: number,
  bgOutputPath: string,
): Promise<void> {
  const pythonPath = config.pythonPath || 'python3';
  let expectedFrames = 0;

  await runSubprocess({
    command: pythonPath,
    args: [
      scriptPath,
      videoPath,
      '--output', mattePath,
      '--backbone', 'resnet50',
      '--scale', '1.0',            // full resolution for quality
      '--fps', '0',                 // 0 = use source native frame rate
      '--downsample-ratio', '0.8',
      '--start-ms', String(startMs),
      '--end-ms', String(endMs),
      '--bg-output', bgOutputPath,
    ],
    timeoutMs: 15 * 60 * 1000,     // 15 min (full video at full res is slower)
    name: 'segmentation',
    onStdoutLine: (line) => {
      // Parse total frame count from initial log line
      if (!expectedFrames && line.includes('Processing video:')) {
        const totalMatch = line.match(/(\d+) frames/);
        if (totalMatch) {
          expectedFrames = parseInt(totalMatch[1], 10);
        }
      }
      // Parse progress
      if (line.includes('Processed') && line.includes('frames')) {
        const match = line.match(/Processed (\d+) frames/);
        if (match) {
          const processed = parseInt(match[1], 10);
          const total = expectedFrames || processed * 2;
          const ratio = Math.min(1, processed / total);
          const progress = Math.min(80, 22 + Math.round(ratio * 58));
          publishJobProgress(jobId, progress, `Segmenting: ${processed} frames processed`, { projectId, sceneId });
        }
      }
    },
  });
}
