ALTER TABLE projects
ADD COLUMN IF NOT EXISTS workspace_status VARCHAR(50) NOT NULL DEFAULT 'inactive',
ADD COLUMN IF NOT EXISTS workspace_last_activity TIMESTAMP,
ADD COLUMN IF NOT EXISTS active_bundle_url VARCHAR(1024);

ALTER TABLE visuals
ADD COLUMN IF NOT EXISTS source_scene_ids JSONB;
